name: SolarUHC
version: 1.0.0
author: solarlego
main: me.solarlego.uhc.UHC
depend:
  - SolarMain
commands:
  play:
    usage: "\u00a7cUsage: /<command> <game>"
    description: Transfers the sender into a game
    aliases: join
  end:
    usage: "\u00A7cUsage: /<command>"
    description: Ends the current game
    permission: solarlego.command.end
  teams:
    usage: "\u00A7cUsage: /<command>"
    description: Displays the teams menu in UHC
    aliases: team
  kits:
    usage: "\u00A7cUsage: /<command>"
    description: Displays the kits menu in UHC
    aliases: kit
  recipes:
    usage: "\u00A7cUsage: /<command>"
    description: Displays the recipes menu in UHC
    aliases: [recipe, crafts, craft]
